services:
  compiler:
    image: wingzzz2003/compiler:beta
    tty: true
    stdin_open: true
    entrypoint: ["/bin/bash"]
    environment:
      - DISPLAY=${DISPLAY}
      #- DISPLAY=host.docker.internal:0.0
      #- WAYLAND_DISPLAY=$WAYLAND_DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - sourcecode:/home/ubuntu/sourcecode
      - m2cache:/home/ubuntu/.m2
      #- $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY
    ports:
      - 8080:8080

volumes:
  sourcecode:
  m2cache:

# steamdeck
# xhost +local:
# podman container run -e DISPLAY=${DISPLAY} \
# -v /tmp/.X11-unix:/tmp/.X11-unix:rw -it --entrypoint /bin/bash \
# --network=host \
# --rm docker.io/wingzzz2003/compiler:beta

# windows + mobilexterm
# enable DISPLAY=host.docker.internal:0.0
# disable DISPLAY=${DISPLAY}
# disable /tmp/.X11-unix:/tmp/.X11-unix:rw

# ubuntu
# enable WAYLAND_DISPLAY=$WAYLAND_DISPLAY
# disable DISPLAY=${DISPLAY}